const cards: any = [
  {
    image: 'https://hvost.news/upload/resize_cache/iblock/b38/750_400_1/sibirskij_haski.jpg',
    name: 'cибирский хаски',
    nameEnglish: 'siberian husky',
    country: 'Россия',
    weight: '20-28 кг (самцы), 15-23 кг (самки)',
    growth: '55-60 см (самцы), 50-55 см (самки)',
    age: '12-15 лет',
  },
  {
    image: 'https://wikipet.ru/wp-content/uploads/2018-03/1520854554_yorkshire-terrier-weight.jpg',
    name: 'йоркширский терьер',
    nameEnglish: 'yorkshire terrier',
    country: 'Англия',
    weight: '2-3,2 кг',
    growth: '15-17 см',
    age: '12-15 лет',
  },
  {
    image:
      'https://hvost.news/upload/resize_cache/iblock/4ae/750_400_1/4ae47339952d9aea47fa277932805ede.jpg',
    name: 'золотистый ретривер',
    nameEnglish: 'golden retriever',
    country: 'Великобритания',
    weight: '25-37 кг (самки), 26-41 кг (самцы)',
    growth: '51-56 см (самки), 56-61 см (самцы)',
    age: '12-13 лет',
  },
  {
    image: 'https://www.petstopdog.info/wp-content/uploads/tea-cup-chihuahua-e1621766336743.jpeg',
    name: 'чихуахуа',
    nameEnglish: 'chihuahua',
    country: 'Мексика',
    weight: '0,5-3 кг',
    growth: '15-23 см',
    age: '11-14 лет',
  },
  {
    image: 'https://pitomec.guru/wp-content/uploads/2018/02/taksa-CaptureLight-360x280.jpg',
    name: 'такса',
    nameEnglish: 'dachshund',
    country: 'Германия',
    weight: 'до 12 кг',
    growth: 'до 35 см',
    age: '10-13 лет',
  },
  {
    image: 'https://i.ytimg.com/vi/BlNDWyazBXw/maxresdefault.jpg',
    name: 'немецкая овчарка',
    nameEnglish: 'german shepherd',
    country: 'Германия',
    weight: '22-32 кг (самки), 30-40 кг (самцы)',
    growth: '55-60 см (самки), 60-65 см (самцы)',
    age: '10-13 лет',
  },
  {
    image: 'https://dogtail.org/wp-content/uploads/2019/08/pomeranets3.jpg',
    name: 'померанский шпиц',
    nameEnglish: 'pomeranian pygmy',
    country: 'Германия',
    weight: '1,4-3,2 кг',
    growth: '18-22 см',
    age: '12-16 лет',
  },
  {
    image: 'https://royal-groom.ru/sites/default/files/breed/akitainu.jpg',
    name: 'акита-ину',
    nameEnglish: 'akita inu',
    country: 'Япония',
    weight: '23-39 кг',
    growth: '58-64 см (самки), 64-70 см (самцы)',
    age: '10-12 лет',
  },
  {
    image:
      'https://vesti.dp.ua/wp-content/uploads/2018/01/%D1%81%D0%BE%D0%B1%D0%B0%D0%BA%D0%B0111.jpg',
    name: 'ротвейлер',
    nameEnglish: 'rottweiler',
    country: 'Германия',
    weight: 'до 45 кг (самки), до 50 кг (самцы)',
    growth: '56-65 см (самки), 61-70 см (самцы)',
    age: '11-12 лет',
  },
  {
    image: 'https://egida.by/_pu/8/19590977.jpg',
    name: 'английский кокер-спаниель',
    nameEnglish: 'english cocker spaniel',
    country: 'Великобритания',
    weight: '13-14,5 кг',
    growth: '38-39 см (самки), 39-41 см (самцы)',
    age: '13-14 лет',
  },
];

export default cards;
